// Demo data for Auto-Negotiation feature
import type { VendorIntel } from './types';

export const VENDOR_INTELLIGENCE: Record<string, VendorIntel> = {
  Netflix: {
    generosityScore: 72,
    negotiationDifficulty: 'Medium',
    avgDiscount: 25,
    bestDay: 'Tuesday',
    bestTime: '2-4 PM EST',
    winBackLikelihood: 89,
    retentionBudget: 'High (Q1)',
    priceFloor: 9.99,
    crowdSourcedTips: ['Mention competitor pricing', 'Ask for loyalty discount', 'Threaten to switch to ad tier'],
  },
  Spotify: {
    generosityScore: 65,
    negotiationDifficulty: 'Easy',
    avgDiscount: 30,
    bestDay: 'Wednesday',
    bestTime: '10 AM-12 PM EST',
    winBackLikelihood: 92,
    retentionBudget: 'Very High',
    priceFloor: 5.99,
    crowdSourcedTips: ['Compare to Apple Music', 'Student discount probe', 'Family plan leverage'],
  },
  'Adobe Creative Cloud': {
    generosityScore: 45,
    negotiationDifficulty: 'Hard',
    avgDiscount: 40,
    bestDay: 'Friday',
    bestTime: '3-5 PM EST',
    winBackLikelihood: 78,
    retentionBudget: 'Medium',
    priceFloor: 29.99,
    crowdSourcedTips: ['Annual commitment gets best rates', 'Photography plan as alternative', 'Educational pricing'],
  },
  'Disney+': {
    generosityScore: 58,
    negotiationDifficulty: 'Medium',
    avgDiscount: 20,
    bestDay: 'Monday',
    bestTime: '11 AM-1 PM EST',
    winBackLikelihood: 85,
    retentionBudget: 'High',
    priceFloor: 7.99,
    crowdSourcedTips: ['Bundle with Hulu mention', 'Annual plan savings', 'Competitor content gaps'],
  },
  'Amazon Prime': {
    generosityScore: 52,
    negotiationDifficulty: 'Hard',
    avgDiscount: 15,
    bestDay: 'Thursday',
    bestTime: '9-11 AM EST',
    winBackLikelihood: 95,
    retentionBudget: 'Very High',
    priceFloor: 10.99,
    crowdSourcedTips: ['Student/EBT discount', 'Prime Video only option', 'Shipping-only benefits'],
  },
  'HBO Max': {
    generosityScore: 68,
    negotiationDifficulty: 'Medium',
    avgDiscount: 28,
    bestDay: 'Tuesday',
    bestTime: '1-3 PM EST',
    winBackLikelihood: 87,
    retentionBudget: 'High',
    priceFloor: 9.99,
    crowdSourcedTips: ['Mention limited content updates', 'Compare to Netflix originals', 'Annual plan request'],
  },
  'YouTube Premium': {
    generosityScore: 55,
    negotiationDifficulty: 'Medium',
    avgDiscount: 22,
    bestDay: 'Wednesday',
    bestTime: '2-4 PM EST',
    winBackLikelihood: 82,
    retentionBudget: 'Medium',
    priceFloor: 8.99,
    crowdSourcedTips: ['Family plan conversion', 'Student eligibility', 'YouTube Music bundle value'],
  },
};

export const NEGOTIATION_SCRIPTS: Record<string, Array<{ role: 'ai' | 'rep'; message: string; turn?: number }>> = {
  Netflix: [
    { role: 'ai', message: "Hi! I'm reaching out on behalf of a loyal Netflix customer who's been subscribed for over 2 years.", turn: 1 },
    { role: 'rep', message: "Hello! Thank you for contacting Netflix support. How can I help you today?", turn: 1 },
    { role: 'ai', message: "My customer is considering canceling due to recent price increases. They love the service but are looking to reduce monthly expenses.", turn: 2 },
    { role: 'rep', message: "I understand. Let me check what options we have available...", turn: 2 },
    { role: 'ai', message: "[STRATEGY: Competitor Mention] They've been comparing prices with Disney+ and HBO Max bundles.", turn: 3 },
    { role: 'rep', message: "I see. We definitely want to keep you as a customer. Let me check our retention offers.", turn: 3 },
    { role: 'rep', message: "I can offer a 20% discount for the next 6 months. Would that work?", turn: 4 },
    { role: 'ai', message: "[STRATEGY: Push for More] That's a great start! Could we possibly extend that to 12 months given their loyalty?", turn: 5 },
    { role: 'rep', message: "Let me speak with my supervisor about that...", turn: 5 },
    { role: 'rep', message: "I can do 25% off for 12 months. That's our best retention offer.", turn: 6 },
    { role: 'ai', message: "[STRATEGY: Accept & Confirm] Perfect! My customer accepts. Thank you for your help!", turn: 7 },
  ],
  Spotify: [
    { role: 'ai', message: "Hello! I'm negotiating on behalf of a Premium subscriber who's been with Spotify for 18 months.", turn: 1 },
    { role: 'rep', message: "Hi there! How can I assist you?", turn: 1 },
    { role: 'ai', message: "[STRATEGY: Competitor Comparison] They're comparing prices with Apple Music and considering switching.", turn: 2 },
    { role: 'rep', message: "Let me look into your account... I see you've been a great customer.", turn: 2 },
    { role: 'rep', message: "I can offer 3 months at 50% off.", turn: 3 },
    { role: 'ai', message: "[STRATEGY: Counter Offer] That's helpful! Can we make it 6 months?", turn: 4 },
    { role: 'rep', message: "I can do 4 months at 50% off. Final offer!", turn: 4 },
    { role: 'ai', message: "Deal! Thank you for working with us.", turn: 5 },
  ],
  default: [
    { role: 'ai', message: "Hi! I'm reaching out about a subscription price negotiation.", turn: 1 },
    { role: 'rep', message: "Hello! How can I help you today?", turn: 1 },
    { role: 'ai', message: "My customer is a loyal subscriber looking to reduce their monthly bill.", turn: 2 },
    { role: 'rep', message: "I understand. Let me check what discounts are available...", turn: 2 },
    { role: 'ai', message: "[STRATEGY: Competitor Analysis] They've been researching alternative services in the market.", turn: 3 },
    { role: 'rep', message: "I can offer a 15% discount for the next 6 months.", turn: 3 },
    { role: 'ai', message: "[STRATEGY: Counter Offer] Is there any way to improve on that?", turn: 4 },
    { role: 'rep', message: "I can do 20% off for 6 months. That's my best offer.", turn: 4 },
    { role: 'ai', message: "Thank you! That works for us.", turn: 5 },
  ],
};
